/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("org.springframework.boot") version "3.5.6"
    id("io.spring.dependency-management") version "1.1.6"
    java
}
group = "com.example"
version = "0.0.1-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")   // Webアプリ用
    implementation("org.springframework.boot:spring-boot-starter-validation")// validation
    testImplementation("org.springframework.boot:spring-boot-starter-test") // テスト用
    developmentOnly("org.springframework.boot:spring-boot-devtools")// ホットリロードみたいな
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")//DB
    runtimeOnly("com.h2database:h2")// h2 DB使用していまっせ。
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}